name: coverage
on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest

    env:
      HOOTSIM_PATH: "."

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Install requirements
      run: |
        sudo apt-get update -q
        sudo apt-get install libyaml-cpp-dev -y
        sudo apt-get install bc -y

    - name: Evaluate coverage
      run: |
        make coverage > coverage_output.txt
        cat coverage_output.txt

        COVERAGE=$(make coverage | grep 'TOTAL COVERAGE' | grep -Eo '[0-9]+')

        if [ "$COVERAGE" -gt 89 ]; then
            echo "success"
        else
            echo "failure"
            exit 1
        fi
