name: test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run tests
      run: |
        result=$(make test)
        echo "$result"
        echo "::set-output name=test-result::$result"
  
