name: test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      HOOTSIM_PATH: "."

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install requirements
      run: |
        sudo apt-get update -q
        sudo apt-get install libyaml-cpp-dev -y

    - name: Run tests
      run: |
        result=$(make test)
        echo "$result"
        echo "::set-output name=test-result::$result"
  
